### ISSUE TITLE
SSR should include styles from assets

### ISSUE THREAD

**Issue by Harper04** [seagull-js/seagull#21]

**Comment by Anonyfox** [comment]
bonus points: for AMP seagull needs to render all styles (external sheets or inline, whatever) into a single `<style />` block in the head of the page. There shall only be this style block and nothing else... since there is no JS allowed on AMP pages, interactive stuff (doing anomations, ...) doesn't matter after initial render. 

Usual SSR pages can work as we wish.

**Comment by Harper04** [comment]
without bonus point for now https://github.com/seagull-js/seagull-cli/commit/fc34fdb609d8f9cfd81e544245af1f4a24bba8f8

https://github.com/nfl/react-helmet could be an easy and nice way to integrate everything but we need to change layout.tsx

**Comment by Harper04** [comment]
does not apply anymore
